### ISSUE TITLE
Polls on Zoom

### ISSUE THREAD

**Issue by ocaisa** [carpentrycon/carpentrycon2020#92]
For our session, we would like to use a Zoom poll, will we have the rights to create this ourselves?

We would also like to trial how this would/could work. Ideally we would like to take the poll at the beginning, close it, pull the spreadsheet of the results (it's not clear from the Zoom docs if this is actually possible without closing the session), run them through a script and generate some plots for people to discuss during the breakout rooms.

cc-ing @psteinb

**Comment by serahkiburu** [comment]
great question @ocaisa, tagging @maneesha from The Carpentries Infrastructure Team

**Comment by maneesha** [comment]
It is possible to use polls in any Zoom meeting.  To use polls you have to host as  a fully logged in user (with the username and password), not just by claiming the host key. This feature is available to Core Team members only.  If a Core Team member is on the call, we can make this work.  Otherwise it is not possible. 

Note I'm not sure off the top of my head how polling data can be extracted if people want to run scripts on it.  If you think a Core Team member will be able to support a session by doing this, I can look into it more.   

There other online polling tools that community members can use instead if this is important to the functioning of the session.

**Comment by psteinb** [comment]
I have a non-free zoom account (but am not part of the carpentries core team). Would that be sufficient?

**Comment by ocaisa** [comment]
@maneesha Is there a recommended tool? Otherwise, I will probably just go with socrative since I've used it before.

**Comment by maneesha** [comment]
@ocaisa  I'd definitely recommend using a tool you are already familiar with, so using Socrative is a great idea.

@psteinb If you have a paid Zoom account you may have access to polls, but then the event would have to be hosted by your Zoom account, not ours.

**Comment by psteinb** [comment]
@maneesha it doesn't matter to me which zoom account to use. To the best of my knowledge @ocaisa opted for Socrative. Hence, it's fine to use the zoom account of the carpentries. This way, the details of the connection and everything can be deployed centrally including the crowdcast setup etc.

**Comment by maneesha** [comment]
Closing this as outdated. Feel free to re-open if it still needs discussion.
